# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c12145066ea154ca5247b783cd4c0876cac8fc47613b7ade289d6a55e021ffb75ef8c814ef03225d787c41429ee7583faaa87fd96c42749dd86af088c810a83

test:
  secret_key_base: ca1d17781d3a761fcca9561658633e5d789db9d3e4c41c8497cd13cc86868f728d5003e4752da590da1ad12d2a12c5912aadcb0983fa59814d8ba5d02496f1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
